"""Public API for the Python minimalist installer."""

from importlib import metadata as _metadata

from .core import (
    CheckpointWriter,
    CorruptManifestError,
    CorruptTransactionError,
    Driver,
    Effect,
    EffectContext,
    EffectPlan,
    EffectProgress,
    EffectRegistry,
    ErrorCode,
    GreenfieldConflictError,
    IncompleteTransactionError,
    InstallResult,
    InstallerError,
    Installer,
    InvalidEffectError,
    InvalidPlanError,
    InvalidDistributionError,
    JsonObject,
    JsonScalar,
    JsonValue,
    LockTimeoutError,
    ModifiedContentError,
    NoInstallationError,
    NoHostDetectedError,
    NonInteractiveInputRequiredError,
    Operation,
    OperationResult,
    OperationStatus,
    PlanContext,
    PreparedEffect,
    Provider,
    RecoveryBlockedError,
    RepairResult,
    StatusResult,
    JournalCheckpoint,
    TransactionEffectRecord,
    TransactionJournal,
    TransactionPhase,
    TransactionRepository,
    UninstallResult,
    UnknownEffectError,
    UnsafePathError,
    UnsupportedEffectVersionError,
    UnsupportedHostError,
    UpdateResult,
    define_installer,
)
from .providers import FileSetProvider

__all__ = [
    "CheckpointWriter",
    "CorruptManifestError",
    "CorruptTransactionError",
    "Driver",
    "Effect",
    "EffectContext",
    "EffectPlan",
    "EffectProgress",
    "EffectRegistry",
    "ErrorCode",
    "GreenfieldConflictError",
    "IncompleteTransactionError",
    "InstallResult",
    "InstallerError",
    "Installer",
    "InvalidEffectError",
    "InvalidPlanError",
    "InvalidDistributionError",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "LockTimeoutError",
    "ModifiedContentError",
    "NoInstallationError",
    "NoHostDetectedError",
    "NonInteractiveInputRequiredError",
    "Operation",
    "OperationResult",
    "OperationStatus",
    "PlanContext",
    "PreparedEffect",
    "Provider",
    "RecoveryBlockedError",
    "RepairResult",
    "StatusResult",
    "JournalCheckpoint",
    "TransactionEffectRecord",
    "TransactionJournal",
    "TransactionPhase",
    "TransactionRepository",
    "UninstallResult",
    "UnknownEffectError",
    "UnsafePathError",
    "UnsupportedEffectVersionError",
    "UnsupportedHostError",
    "UpdateResult",
    "FileSetProvider",
    "define_installer",
]

try:
    __version__ = _metadata.version("minimalist-installer")
except _metadata.PackageNotFoundError:
    __version__ = "0+unknown"
