"""Public API for the Python minimalist installer."""

from importlib import metadata as _metadata

from .core import (
    CheckpointWriter,
    CorruptManifestError,
    Effect,
    EffectContext,
    EffectPlan,
    ErrorCode,
    GreenfieldConflictError,
    IncompleteTransactionError,
    InstallResult,
    InstallerError,
    InvalidDistributionError,
    JsonObject,
    JsonScalar,
    JsonValue,
    LockTimeoutError,
    ModifiedContentError,
    NoHostDetectedError,
    NonInteractiveInputRequiredError,
    Operation,
    OperationResult,
    OperationStatus,
    PlanContext,
    PreparedEffect,
    Provider,
    RecoveryBlockedError,
    RepairResult,
    StatusResult,
    UninstallResult,
    UnknownEffectError,
    UnsafePathError,
    UnsupportedEffectVersionError,
    UnsupportedHostError,
    UpdateResult,
)

__all__ = [
    "CheckpointWriter",
    "CorruptManifestError",
    "Effect",
    "EffectContext",
    "EffectPlan",
    "ErrorCode",
    "GreenfieldConflictError",
    "IncompleteTransactionError",
    "InstallResult",
    "InstallerError",
    "InvalidDistributionError",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "LockTimeoutError",
    "ModifiedContentError",
    "NoHostDetectedError",
    "NonInteractiveInputRequiredError",
    "Operation",
    "OperationResult",
    "OperationStatus",
    "PlanContext",
    "PreparedEffect",
    "Provider",
    "RecoveryBlockedError",
    "RepairResult",
    "StatusResult",
    "UninstallResult",
    "UnknownEffectError",
    "UnsafePathError",
    "UnsupportedEffectVersionError",
    "UnsupportedHostError",
    "UpdateResult",
]

try:
    __version__ = _metadata.version("minimalist-installer")
except _metadata.PackageNotFoundError:
    __version__ = "0+unknown"
